<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
    <?php foreach($gambles as $gamble): ?>
        <li>
            <p><?=$gamble->fecha?></p>
            <p><?=$gamble->monto?></p>
            <p><?=$gamble->id_juego?></p>
        </li>
    <?php endforeach; ?>
    </ul>

</body>
</html>