<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post" action="process_gamble">
        <input type="datetime-local" name="date"/>
        <input type="number" name="amount" placeholder="Monto"/>
        <?php foreach($games as $game): ?>
        <label for="<?=$game->nombre?>"><?=$game->nombre?></label>
        <input type="radio" id="<?=$game->nombre?>" name="id_game" value="<?= $game->id ?>"/>
        <?php endforeach; ?>
        <button type="submit">Hacer apuesta</button>
        <div class="<?=$error?>">
            <p><?=$error?></p>
        </div>
    </form>
</body>
</html>